### ISSUE TITLE
Failed to fetch data

### ISSUE THREAD

**Issue by ernsttanaka** [Sikerdebaard/hacs-ducobox-connector#1]
Hi trying your new Duco integration:

I am getting the following error in the logs:

Logger: custom_components.ducobox-connectivity-board.sensor
Source: custom_components/ducobox-connectivity-board/sensor.py:414
integration: ducobox-connectivity-board
First occurred: 12:16:58 PM (14 occurrences)
Last logged: 12:46:58 PM

Failed to fetch data from Ducobox API: HTTPConnectionPool(host='192.168.4.89.local', port=80): Max retries exceeded with url: /info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff16b893bc0>: Failed to establish a new connection: [Errno -5] Name has no usable address'))
Failed to fetch data from Ducobox API: HTTPConnectionPool(host='192.168.4.89.local', port=80): Max retries exceeded with url: /info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff16f5c1130>: Failed to establish a new connection: [Errno -5] Name has no usable address'))
Failed to fetch data from Ducobox API: HTTPConnectionPool(host='192.168.4.89.local', port=80): Max retries exceeded with url: /info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff16f5faa50>: Failed to establish a new connection: [Errno -5] Name has no usable address'))
Failed to fetch data from Ducobox API: HTTPConnectionPool(host='192.168.4.89.local', port=80): Max retries exceeded with url: /info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff16f6d5910>: Failed to establish a new connection: [Errno -5] Name has no usable address'))
Failed to fetch data from Ducobox API: HTTPConnectionPool(host='192.168.4.89.local', port=80): Max retries exceeded with url: /info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff16f46f4d0>: Failed to establish a new connection: [Errno -5] Name has no usable address'))

**Comment by Sikerdebaard** [comment]
1. Are you using a ducobox connectivity board?
2. The integration is trying to connect over port 80 (http) but the connectivity board can only be reached over port 443 (https). Have you added the box manually or automatically through zeroconf / mDNS?

**Comment by ernsttanaka** [comment]
Yes, I have a duco energy premium with a connectivity board. 
the reference for port=80 comes from the integration. 
the Duco was self discovered by HA, I only added it to an area.

**Comment by ernsttanaka** [comment]
here is another error I am also seeing the log:

This error originated from a custom integration.

Logger: custom_components.ducobox-connectivity-board.sensor
Source: custom_components/ducobox-connectivity-board/sensor.py:414
integration: ducobox-connectivity-board
First occurred: 12:59:32 PM (28 occurrences)
Last logged: 1:30:39 PM

Failed to fetch data from Ducobox API: 503 Server Error: for url: https://192.168.4.89/info/nodes
Failed to fetch data from Ducobox API: 10 validation errors for NodesResponse Nodes -> 0 -> General -> Type -> Id field required (type=value_error.missing) Nodes -> 1 -> General -> Type -> Id field required (type=value_error.missing) Nodes -> 2 -> General -> Type -> Id field required (type=value_error.missing) Nodes -> 3 -> General -> Type -> Id field required (type=value_error.missing) Nodes -> 4 -> General -> Type -> Id field required (type=value_error.missing) Nodes -> 5 -> General -> Type -> Id field required (type=value_error.missing) Nodes -> 6 -> General -> Type -> Id field required (type=value_error.missing) Nodes -> 7 -> General -> Type -> Id field required (type=value_error.missing) Nodes -> 8 -> General -> Type -> Id field required (type=value_error.missing) Nodes -> 9 -> General -> Type -> Id field required (type=value_error.missing)
Failed to fetch data from Ducobox API: 503 Server Error: for url: https://192.168.4.89/info

**Comment by Sikerdebaard** [comment]
I've made some adjustments to the code and enabled some extra debugging. Could you try updating and report back if it does or doesn't work? If it doesn't: please enable debugging for this plugin and send me the logs. 

![image](https://github.com/user-attachments/assets/598bc2a0-bcf3-4072-9960-f70b8c238d67)

**Comment by ernsttanaka** [comment]
appreciate the help, it now works - most entities are being populated.

The Duco integration has been split up in 8 devices and which collectively have 38 entities. The box, every CO2 sensor and the BOX RH  have become a device (in my case a total of 8.

After a few minutes it stops working;

Initially I get a warning:

Logger: py.warnings
Source: custom_components/ducobox-connectivity-board/sensor.py:420
integration: ducobox-connectivity-board
First occurred: 3:24:25 PM (6 occurrences)
Last logged: 3:26:41 PM

/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.4.89'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings warnings.warn(


____________

Which then turns into a error:

Logger: custom_components.ducobox-connectivity-board.sensor
Source: custom_components/ducobox-connectivity-board/sensor.py:414
integration: ducobox-connectivity-board
First occurred: 3:29:08 PM (4 occurrences)
Last logged: 3:32:43 PM

Failed to fetch data from Ducobox API: 503 Server Error: for url: https://192.168.4.89/info/nodes
Failed to fetch data from Ducobox API: 503 Server Error: for url: https://192.168.4.89/info

**Comment by Sikerdebaard** [comment]
The InsecureRequestWarning is unlikely to be the culprit here. That's more related to the self-signed certificate that the ducobox connectivity board uses. The root library, ducopy, does not have this issue as it uses certificate pinning to prevent this error. But I haven't gotten certificate pinning working yet from home assistant. HA seems to override some ssl/tls settings. In any case, it is something to fix later. It can wait.

The error 503 happens on my connectivity board as well. I am not sure why it does that. But after a few minutes it works again. Can you verify that it is picking up samples again after a few minutes in your installation? Or is it permanently dysfunctional after this error?

**Comment by ernsttanaka** [comment]
Now after 24 minutes they havent returned

**Comment by ernsttanaka** [comment]
another "find" in the logs

Logger: homeassistant.config_entries
Source: config_entries.py:850
First occurred: 3:37:55 PM (1 occurrences)
Last logged: 3:37:55 PM

Error unloading entry Ducobox (192.168.4.89) for ducobox_connectivity_board
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 850, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ducobox-connectivity-board/__init__.py", line 35, in async_unload_entry
    hass.data[DOMAIN].pop(entry.entry_id)
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DucoPy' object has no attribute 'pop'

**Comment by ernsttanaka** [comment]
on tweeker I read that  503 comes when we poll too often in a time span.  No indication of time span or freq what's regarded too Often.

**Comment by ernsttanaka** [comment]
good morning 
The reading is still intermitted. See the graph from last nights co2 measures on one of my sensors. 
 I have no good indication what this causes. I have reduced the scanning to 5min. 
![IMG_0364](https://github.com/user-attachments/assets/8de4a528-deb4-4179-9053-bd2638dd4fb1)

**Comment by ernsttanaka** [comment]
Installed the lasted version. Still issues with intermittent data. 
I set the scan to 300sec that improves the situation a little

**Comment by Sikerdebaard** [comment]
Is there a way for me to reach out to you privately? I want to send you a resource that might (or might not) help you in debugging this issue.

**Comment by ernsttanaka** [comment]
> Is there a way for me to reach out to you privately? I want to send you a resource that might (or might not) help you in debugging this issue.

Good morning

Appreciate the help. 

A temp email address I have set up is

Temp7512e@icloud.com

Thanks in advance

**Comment by DaanW1990** [comment]
Hi @Sikerdebaard, appreciate your efforts a lot! Very helpful to finally see PPM/temp as well. After installation I retrieved the data for a short time, thereafter no values were retrieved - seems the same issue as in this topic. I'm trying to understand the log, but not sure if I'm looking at the right logs. Hope you can help. I'm really new at coding etc. so this is stretching my capacity.

Also curious if you are considering to include options to control the flow in this connector as well? would be great to set values in the Duco system as well.

see logs below:
AttributeError: 'NoneType' object has no attribute 'get'
2024-11-28 17:06:03.688 ERROR (MainThread) [homeassistant.components.rest.data] Timeout while fetching data: https://192.168.2.78/info/nodes
2024-11-28 17:06:46.516 WARNING (SyncWorker_13) [py.warnings] /usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.2.78'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2024-11-28 17:06:46.623 ERROR (MainThread) [custom_components.ducobox_connectivity_board.sensor] Failed to fetch data from Ducobox API: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-11-28 17:07:47.415 WARNING (SyncWorker_16) [py.warnings] /usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.2.78'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2024-11-28 17:07:49.536 WARNING (SyncWorker_16) [py.warnings] /usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.2.78'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2024-11-28 17:07:51.603 WARNING (SyncWorker_16) [py.warnings] /usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.2.78'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2024-11-28 17:07:54.791 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):

**Comment by ernsttanaka** [comment]
Good morning 

I installed the last version. Indeed now get the "unavailable"'s. 

Also see two new errors in the logs. (See below). 

![image](https://github.com/user-attachments/assets/b791481b-9faf-4e60-af67-4ed025361f1f)


![image](https://github.com/user-attachments/assets/e12133cd-5a1e-48b9-a49c-e319d965829e)

**Comment by DaanW1990** [comment]
Thanks @Sikerdebaard, the update works well. Data is still visible. 

Your suggestion to control data through writing in ducopy library is great. However, I'm really a noob and not sure how to access that library etc. so will wait for an update. 

Appreciate your work! thanks.

**Comment by DaanW1990** [comment]
Sorry I cheered too soon. The data doesn’t seem to update, it just remains at the same level since yesterday 9pm. Sourcing the data through the rest command gives a good comparison, see below example ‘Woonkamer’.

I’m not seeing any particular error in the log, just the standard line that keeps repeating:

2024-11-29 21:04:28.766 WARNING (SyncWorker_20) [py.warnings] /usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.2.78'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(


![IMG_1266](https://github.com/user-attachments/assets/4e69dd56-aa48-458c-8c84-3a4693dfa5e0)

any solution/suggestion?

**Comment by ernsttanaka** [comment]
Good morning 

Are you guys making progress in solving the data access issues?

When do you expect us to be able to set some of the Duco parameters in home assistance. 

I for instance would like to raise the minimum flow level for zone 1 during day time when the living space is in use. That way I have a more constant flow of ventilation and not the "stop" and go I have now. 

Thanks in advance for the hard work. 

Ernst

**Comment by coert** [comment]
For me, since yesterday (jan 1 2025, coincidence?) it's not possible to make a connection to the Connectivity Board on port 443. In fact, it's not even possible for me anymore to use the official Duco Android app which connects to the local WiFi AP (which was always possible before). 

Can anyone confirm they have the same issue? I have a DucoBox Energy Comfort 325 with a Connectivity Board. I suspect some kind of internal certificate became invalid as of jan 1 2025. 

To be clear, before the new year I was able to read all values (including raw CO2 values from my room sensor) after creating an API key and connecting to 443 with the relevant SSL certificate provided here. Every now and again I'd get a 503, but I solved it by adapting this code to retry with delay. Now it's back to square one though.

**Comment by ernsttanaka** [comment]
The Duco installation app and the direct reference to duco_xxx.local still work (even after Jan 1st). 

The ducopy still gives extreme intermittent data results. 
wish original programmers could find a solution for this. 

E.

**Comment by Sikerdebaard** [comment]
> For me, since yesterday (jan 1 2025, coincidence?) it's not possible to make a connection to the Connectivity Board on port 443. In fact, it's not even possible for me anymore to use the official Duco Android app which connects to the local WiFi AP (which was always possible before).
> 
> Can anyone confirm they have the same issue? I have a DucoBox Energy Comfort 325 with a Connectivity Board. I suspect some kind of internal certificate became invalid as of jan 1 2025.
> 
> To be clear, before the new year I was able to read all values (including raw CO2 values from my room sensor) after creating an API key and connecting to 443 with the relevant SSL certificate provided here. Every now and again I'd get a 503, but I solved it by adapting this code to retry with delay. Now it's back to square one though.

@coert did the IP address of your connectivity board perhaps change, or has it somehow disconnected from your WiFi?



> The Duco installation app and the direct reference to duco_xxx.local still work (even after Jan 1st).
> 
> The ducopy still gives extreme intermittent data results. wish original programmers could find a solution for this.
> 
> E.

@ernsttanaka your specific connectivity issues seem local to your setup. It doesn't look like something I can fix. Things you could check for are WiFi connectivity: is the signal strength strong enough? Also make sure you aren't asking too much of the connectivity board. Its a fairly rudementary board with limited compute. E.g. if you have one of those REST scripts running next to this HACS addon then this can easily saturate the capabilities of the board.

My kid just started daycare and I've only been sick the last few weeks so I simply wasn't able to work on this project. This project is a voluntary effort anyways, I am not getting paid for this, so you should set your expectations accordingly.

**Comment by coert** [comment]
> @coert did the IP address of your connectivity board perhaps change, or has it somehow disconnected from your WiFi?
No, definitely still the same. Non-secure (http, port 80) api calls work fine.

**Comment by Sikerdebaard** [comment]
> > @coert did the IP address of your connectivity board perhaps change, or has it somehow disconnected from your WiFi?
> 
> No, definitely still the same. Non-secure (http, port 80) api calls work fine.

Duco Connectivity Board should not expose port 80. Are you sure that you are using this device? https://www.duco.eu/en/products/mechanical-ventilation/accessories/connectivity-board

This library is untested on, and likely incompatible with, the Duco Communication Print. This is the predecessor of the Connectivity Board. The Communication Print usually exposes port 80.

**Comment by coert** [comment]
> > > @coert did the IP address of your connectivity board perhaps change, or has it somehow disconnected from your WiFi?
> > 
> > 
> > No, definitely still the same. Non-secure (http, port 80) api calls work fine.
> 
> Duco Connectivity Board should not expose port 80. Are you sure that you are using this device? https://www.duco.eu/en/products/mechanical-ventilation/accessories/connectivity-board
> 
> This library is untested on, and likely incompatible with, the Duco Communication Print. This is the predecessor of the Connectivity Board. The Communication Print usually exposes port 80.

Really? So, you cannot do this:
![image](https://github.com/user-attachments/assets/ea8b0cac-1a6b-4482-bbe8-ac1dc90ebb64)

That's very odd! It's definitely the Connectivity Board and not the Communication Print. I installed it myself. Which firmware version do you have? Mine is: 19156.7.4.0

**Comment by Sikerdebaard** [comment]
> That's very odd! It's definitely the Connectivity Board and not the Communication Print. I installed it myself. Which firmware version do you have? Mine is: 19156.7.4.0

Very odd indeed!

Looks like the port was opened recently. Its accessible on my box as well. This is new to me.

**Comment by coert** [comment]
Final follow up on this issue: turns out the HTTPS server is separated from the HTTP server. After contact with Duco, they suggested that the formed may have crashed on the Connectivity Board. 

All it took was a full power off and on of the Ducobox for the HTTPS server to come back online. Yes, the age old "have you tried turning it off and on again" ...

**Comment by Sikerdebaard** [comment]
@coert classic. You reallyl had me worried there for a moment that they went for http-only (port 80) in the firmware version on your board. :)

I'd have expected the board to self-monitor and self-heal issues like this, especially considering the price of the board. Bit disappointed with Duco on this one.
